### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by Jojokats** [jodyheavener/Swatches#5]
I have Sketch 3.8.3 and when after entering the Hex colors in the swatches, the folders appear but my artboard remains empty. I tried it a couple of times and even uninstalled, reinstalled and it just won't work.
I entered 5 swatches and the layer panel writes 5 colors but when clicking in the folder, it shows only 1 swatch not the 5 colors I entered and my artboard remains blank, empty.

**Comment by jodyheavener** [comment]
Please see #4
